### ISSUE TITLE
upload script shuffles images

### ISSUE THREAD

**Issue by zdila** [openstreetcam/upload-scripts#22]
Upload script uses `DateTimeOriginal` to order files. If this exif field is missing, it shuffles the files. Problem is also if more files have the same value of `DateTimeOriginal` because script doesn't consider `SubSecTimeOriginal`.

Script could also consider using `GPSTimeStamp` and `GPSDateStamp` fields if above are missing.

**Comment by mprins** [comment]
eg. http://www.openstreetcam.org/details/165078/114

**Comment by bogdan-telenav** [comment]
@mprins This problem persists? 
Thanks for improving osm

**Comment by bogdan-telenav** [comment]
do you still have this problem??

**Comment by mprins** [comment]
I tried again and no luck uploading at all.. sit seems to hang for a while at
```
Retry attempt : 248
Retry attempt : 247
Retry attempt : 246
Retry attempt : 249
Retry attempt : 249
Retry attempt : 248
Retry attempt : 250
Retry attempt : 247
Retry attempt : 250
Retry attempt : 249
```
and than again at some 120 or so higher, and again and again etc.., basically exhausting sockets and then waiting. There is no feedback as to what is going on.. and no indication when the script will finish if at all

```
Retry attempt : 1694
Retry attempt : 1727
Retry attempt : 1593
Retry attempt : 1572
Retry attempt : 1695
Retry attempt : 1728
Retry attempt : 1594
Retry attempt : 1573
Retry attempt : 1696
Retry attempt : 1729
Retry attempt : 1595
Retry attempt : 1574
Retry attempt : 1697
```

So the original problem does no longer occur because uploading fails at all

**Comment by mprins** [comment]
I tried the docker command with limited succes:
```
docker run -it --rm -v /mnt/XXXXXXX/2017_04_26_14_40_37_931/:/data openstreetcam/upload_photos_by_exif

```
which seemed to start uploading OK (after removing the left behind count and seq id file) but checking the website things are still messed up for this sequence (http://www.openstreetcam.org/details/930585/0)

**Comment by mprins** [comment]
and a smalll one with images that have direction info as well: http://www.openstreetcam.org/details/930591/0 


note to self: 2017_04_26_11_16_19_768

**Comment by bogdan-telenav** [comment]
@mprins Sorry about this. Can you provide some images?  Thanks!!!

**Comment by mprins** [comment]
@bogdan-telenav I've uploaded the images of that last sequence to WeTransfer: https://we.tl/2TDKx3ZkQ3

**Comment by bogdans-telenav** [comment]
We made major changes to the previous version of the script and we now take into consideration GPS time stamp, so this is most likely fixed. If you find any other problem please create a new issue.

**Comment by mishari** [comment]
![0000001](https://user-images.githubusercontent.com/503018/53042537-10fb2780-34b9-11e9-9b29-98598d823288.jpg)
![0000002](https://user-images.githubusercontent.com/503018/53042546-15274500-34b9-11e9-92e7-7b54887c9903.jpg)
![0000003](https://user-images.githubusercontent.com/503018/53042547-15274500-34b9-11e9-963b-e8c6fd3f11ee.jpg)
![0000004](https://user-images.githubusercontent.com/503018/53042548-15bfdb80-34b9-11e9-8995-bd6c77e9537c.jpg)
![0000005](https://user-images.githubusercontent.com/503018/53042550-15bfdb80-34b9-11e9-9765-f829e88fa85d.jpg)
![0000006](https://user-images.githubusercontent.com/503018/53042551-15bfdb80-34b9-11e9-9147-682e06ec10df.jpg)
![0000007](https://user-images.githubusercontent.com/503018/53042552-16587200-34b9-11e9-9b5e-79950d10b2d5.jpg)
![0000008](https://user-images.githubusercontent.com/503018/53042554-16587200-34b9-11e9-9374-7e62e4f56f9f.jpg)
![0000009](https://user-images.githubusercontent.com/503018/53042555-16587200-34b9-11e9-968e-1f323e2d8267.jpg)
[OSC_logs.log](https://github.com/openstreetcam/upload-scripts/files/2881738/OSC_logs.log)
