### ISSUE TITLE
Upload scripts no longer work

### ISSUE THREAD

**Issue by james2432** [openstreetcam/upload-scripts#27]
This is the error code received from api:
![image](https://cloud.githubusercontent.com/assets/498547/22261869/a3188968-e23c-11e6-865e-cbdaac7e77c7.png)

The image has GPSImgDirection latitude and longitude.

C:\pyscripts\openstreetview>python upload_photos_by_exif.py -p C:\pyscripts\openstreetview\5\1
No sequence file existing
Found 917 pictures to upload
Request/Response fail
Retry attempt : 0
Request/Response fail
Retry attempt : 0
Request/Response fail
Retry attempt : 0
Request/Response fail
Retry attempt : 0
Retry attempt : 1
Retry attempt : 1
Retry attempt : 1
Retry attempt : 1
Retry attempt : 2
Retry attempt : 2
Retry attempt : 2
Retry attempt : 2
Retry attempt : 3
Retry attempt : 3
Retry attempt : 3
Retry attempt : 3
Retry attempt : 4
Retry attempt : 4
Retry attempt : 4
Retry attempt : 4
Retry attempt : 5
Retry attempt : 5
Retry attempt : 5
Retry attempt : 5
Retry attempt : 6
Retry attempt : 6
Retry attempt : 6
Retry attempt : 6
Retry attempt : 7
Retry attempt : 7
Retry attempt : 7
Retry attempt : 7
Retry attempt : 8
Retry attempt : 8
Retry attempt : 8
Retry attempt : 8
Retry attempt : 9
Retry attempt : 9
Retry attempt : 9
Retry attempt : 9
Retry attempt : 10
Retry attempt : 10
Retry attempt : 10
Retry attempt : 10
Retry attempt : 11
Retry attempt : 11
Retry attempt : 11
Retry attempt : 11
Retry attempt : 12
Retry attempt : 12
Retry attempt : 12
Retry attempt : 12
Retry attempt : 13
Retry attempt : 13
Retry attempt : 13
Retry attempt : 13
Retry attempt : 14
Retry attempt : 14
Retry attempt : 14
Retry attempt : 14
Retry attempt : 15
Retry attempt : 15
Retry attempt : 15
Retry attempt : 15
Retry attempt : 16
Retry attempt : 16
Retry attempt : 16
Retry attempt : 16
Retry attempt : 17
Retry attempt : 17
Retry attempt : 17
Retry attempt : 17
Retry attempt : 18
Retry attempt : 18
Retry attempt : 18
Retry attempt : 18
Retry attempt : 19
Retry attempt : 19
Retry attempt : 19
Retry attempt : 19
Retry attempt : 20
Retry attempt : 20
Retry attempt : 20
Retry attempt : 20
Retry attempt : 21
Retry attempt : 21
Retry attempt : 21
Retry attempt : 21
Retry attempt : 22
Retry attempt : 22
Retry attempt : 22
Retry attempt : 22
Retry attempt : 23
Retry attempt : 23
Retry attempt : 23
Retry attempt : 23
Retry attempt : 24
Retry attempt : 24
Retry attempt : 24
Retry attempt : 24
Retry attempt : 25
Retry attempt : 25
Retry attempt : 25
Retry attempt : 25
Retry attempt : 26
Retry attempt : 26
Retry attempt : 26
Retry attempt : 26
Retry attempt : 27
Retry attempt : 27
Retry attempt : 27
Retry attempt : 27
Retry attempt : 28
Retry attempt : 28
Retry attempt : 28
Retry attempt : 28
Retry attempt : 29
Retry attempt : 29
Retry attempt : 29
Retry attempt : 29
Retry attempt : 30
Retry attempt : 30
Retry attempt : 30
Retry attempt : 30
Retry attempt : 31
Retry attempt : 31
Retry attempt : 31
Retry attempt : 31
Retry attempt : 32
Retry attempt : 32
Retry attempt : 32
Retry attempt : 32
Retry attempt : 33
Retry attempt : 33
Retry attempt : 33
Retry attempt : 33
Retry attempt : 34
Retry attempt : 34
Retry attempt : 34
Retry attempt : 34
Retry attempt : 35
Retry attempt : 35
Retry attempt : 35
Retry attempt : 35
Retry attempt : 36
Retry attempt : 36
Retry attempt : 36
Retry attempt : 36
Retry attempt : 37
Retry attempt : 37
Retry attempt : 37
Retry attempt : 37
Retry attempt : 38
Retry attempt : 38
Retry attempt : 38
Retry attempt : 38
Retry attempt : 39
Retry attempt : 39
Retry attempt : 39
Retry attempt : 39
Retry attempt : 40
Retry attempt : 40
Retry attempt : 40
Retry attempt : 40
Retry attempt : 41
Retry attempt : 41
Retry attempt : 41
Retry attempt : 41
Retry attempt : 42
Retry attempt : 42
Retry attempt : 42
Retry attempt : 42
Retry attempt : 43
Retry attempt : 43
Retry attempt : 43
Retry attempt : 43
Retry attempt : 44
Retry attempt : 44
Retry attempt : 44
Retry attempt : 44
Retry attempt : 45
Retry attempt : 45
Retry attempt : 45
Retry attempt : 45
Retry attempt : 46
Retry attempt : 46
Retry attempt : 46
Retry attempt : 46
Retry attempt : 47
Retry attempt : 47
Retry attempt : 47
Retry attempt : 47
Retry attempt : 48
Retry attempt : 48
Retry attempt : 48
Retry attempt : 48
Retry attempt : 49
Retry attempt : 49
Retry attempt : 49
Retry attempt : 49
Retry attempt : 50
Retry attempt : 50
Retry attempt : 50
Retry attempt : 50
Retry attempt : 51
Retry attempt : 51
Retry attempt : 51
Retry attempt : 51
Retry attempt : 52
Retry attempt : 52
Retry attempt : 52
Retry attempt : 52
Retry attempt : 53
Retry attempt : 53
Retry attempt : 53
Retry attempt : 53
Retry attempt : 54
Retry attempt : 54

**Comment by james2432** [comment]
Seems to be doing the same on mobile as well

**Comment by bogdan-telenav** [comment]
I will investigate this issue 👍. Thanks for reporting.

**Comment by james2432** [comment]
Seems to be working now.
