### ISSUE TITLE
corrupted field messages

### ISSUE THREAD

**Issue by danbjoseph** [openstreetcam/upload-scripts#42]
using `upload_photos_by_exif.py` in a `virtualenv`
getting lots of the following three messages
```
Possibly corrupted field InteroperabilityVersion in Interoperability IFD
Possibly corrupted field Tag 0x0000 in Interoperability IFD
Possibly corrupted field Tag 0x5ACF in Interoperability IFD
```
then it starts uploading
```
No sequence file existing
Found 1001 pictures to upload
processing DSC02853.JPG
Uploaded - 1 of total :1001, percentage: 0.1% ET:...
processing DSC02854.JPG
Uploaded - 2 of total :1001, percentage: 0.2% ET:...
processing DSC02852.JPG
```
i guess it's a non-critical message?

example picture
![dsc02885](https://user-images.githubusercontent.com/4806884/29594100-a61954fe-877c-11e7-9ca1-5e7416731537.JPG)

**Comment by bogdan-telenav** [comment]
No this is not a critical issue. Very probably there are some differences between versions of exif. Thanks for reporting.
