### ISSUE TITLE
upload_photos_by_exif.py generates HTTP error 500

### ISSUE THREAD

**Issue by ltog** [openstreetcam/upload-scripts#43]
Just before I tried to upload some pictures using `upload_photos_by_exif.py` but got the following message:

```
No sequence file existing
Found 3714 pictures to upload
Request/Response fail
Retry attempt : 0
Request/Response fail
Retry attempt : 0
Request/Response fail
Retry attempt : 0
Retry attempt : 1
Retry attempt : 2
Retry attempt : 1
Retry attempt : 3
Retry attempt : 2
Retry attempt : 3
Retry attempt : 4
Retry attempt : 4
Retry attempt : 5
Retry attempt : 6
[left out similar messages]
```

Wireshark shows POST requests to `/1.0/photo/` using `Host: openstreetcam.com` being answered with an HTTP error 500. This implies the server has a problem.

Can someone confirm this behaviour?

**Comment by bogdan-telenav** [comment]
Hi can you give me some images to test?? Thanks for reporting 👍

**Comment by ltog** [comment]
The problem didn't occur anymore. I will report again if it does. I guess for the moment this issue can be closed.

**Comment by bogdan-telenav** [comment]
Ok i will close this issue for now. Thanks for mapping
