### ISSUE TITLE
Upload script uploads files twice

### ISSUE THREAD

**Issue by britiger** [openstreetcam/upload-scripts#46]
I run upload_exif.py for Uploading files auf Garmin Virb Ultra 30. After the script reached 100% it makes a linebreak. After the linebreak the script continues to upload the files a second time in an disorder to the same track. I need to kill the process at this point.

```
python3 upload_exif.py -p /media/daten/photos/mapillary/2017-10-21/complete/ -t 1
Found 76 pictures to upload
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 76/76 remaining:00:00  elapsed:10:42
```

**Comment by ToeBee** [comment]
I was about to open an issue about this as well. I think it has been happening for a while but I had some weirdness on my local files that I thought might be contributing to it. But I sorted that out and it is definitely duplicating things. This track is only supposed to have 2325 pictures in it. The upload ended up erroring out with a connection timeout after uploading 3293 pictures:
http://openstreetcam.com/details/944735/1

You can see the trace is a mess with out of order pictures all over the place.
