### ISSUE TITLE
Upload script skips pictures on upload error

### ISSUE THREAD

**Issue by ToeBee** [openstreetcam/upload-scripts#48]
I just had the upload script fail on two tracks with the unhelpful `Request/Response fail` message (maybe at least print out the HTTP status code with that message?) and it went into the infinite retry loop. So I had to kill the upload. I restarted the script and it resumed and reported that it had uploaded all of the images but when I checked my user profile, I noticed that there were fewer images on the server than there should have been. 

Track [956741](http://openstreetcam.com/details/956741/1) has 3,837 instead of 3,883 (difference of 46)

Track [956745](http://openstreetcam.com/details/956745/1) has 2,454 instead of 2,465 (difference of 11)

I brought my laptop to work so I am on a large upload pipe and was using 10 upload threads.

Since bandwidth is not an issue right now, I have re-uploaded them as track [956793](http://openstreetcam.com/details/956793/1) and [956823](http://openstreetcam.com/details/956823/1). I will eventually delete the tracks with the missing images.

**Comment by bogdans-telenav** [comment]
@ToeBee this was a upload script issue. Started work on a new script to fix this issues.

**Comment by bogdans-telenav** [comment]
Finally done it! Thanks for your patience! If you find any issues with the new version please create a issue and we will address it as soon as possible.
