### ISSUE TITLE
Unable to upload photos by exif using the Docker image

### ISSUE THREAD

**Issue by n76** [openstreetcam/upload-scripts#52]
I have tried the following where the photos I would like to upload are in the ~/Desktop/2018_0522_140959_887/ folder/directory:
 
    > docker run -it --rm -v 2018_0522_140959_887/ openstreetcam/upload_photos_by_exif
    > docker run -it --rm -v 2018_0522_140959_887/:/data openstreetcam/upload_photos_by_exif
    > docker run -it --rm -v /Users/n76/Desktop/2018_0522_140959_887/ openstreetcam/upload_photos_by_exif
    > docker run -it --rm -v "/Users/n76/Desktop/2018_0522_140959_887/:/data" openstreetcam/upload_photos_by_exif
    > docker run -it --rm -v /Users/n76/Desktop/2018_0522_140959_887 openstreetcam/upload_photos_by_exif

The second one fails on the CLI as Macintoshes don't support a ":" in a file path. All of the others end up giving me the prompt of the form (the oauth_token string is different each time):

    For login go to this URL in your browser:
    http://www.openstreetmap.org/oauth/authorize?oauth_token=RAHZAWTVlQcaURbTT7mx6s9dUgm8Qb5T7u3Abv6A
    Login and  grant acces then press ENTER

I open a browser where I am logged into OSM, paste the URL and authorize. I get a message on my browser that "You have granted application OpenStreetCam access to your account."

I go back to the terminal and press enter. After a delay, I get the following:

    "Decoder failed to handle oauth_token with data as returned by provider. A different decoder may be needed. Provider returned: b''"
    ERROR LOGIN no GRANT ACCES

What am I doing wrong?

And, by the way, "Login and  grant acces then press ENTER" should be changed to "Login and grant access then press ENTER".

**Comment by bogdans-telenav** [comment]
@n76 OSM changed some OAuth related things. We are trying to figure it out on mobile and after that we will fix it also on the client side. 
Firstly the request should be using **https** not **http**.

**Comment by n76** [comment]
Seems like neither the scripts nor the Docker image have been updated in quite a while.

My "workaround" was to submit my photos to Mapillary. . .

**Comment by cliffordsnow** [comment]
Mapillary upload is also broke https://github.com/mapillary/mapillary_tools/issues/236

**Comment by bogdans-telenav** [comment]
Fixed. It was related to a change in the OSM OAuth service.

**Comment by n76** [comment]
When I try to use the scripts directly, not in a Docker image, it seems to get past the AUTH/login step. The script finishes almost instantly with no error messages and no logging/status updates. And when I log into OpenStreetView it does not show any photos as having been uploaded or in progress for upload.

Is this the same problems or a different one?

In any case, it looks like you need to update your Docker image to use the correction on the OSM login/authorization.
