### ISSUE TITLE
oauth failure with docker, upload_photos_by_exif

### ISSUE THREAD

**Issue by rwelty1889** [openstreetcam/upload-scripts#59]
MacOS 10.13.5, Docker 18.03.1-ce-mac65

i clip out the provided URL, enter it into my browser and click on Grant, and get the Authorization request allowed screen. i return to the terminal window and press enter and am informed that oauth has failed:

rwelty$ docker run -it --rm -v "$IP":/data openstreetcam/upload_photos_by_exif

For login go to this URL in your browser:
http://www.openstreetmap.org/oauth/authorize?oauth_token=af3xUy44YkyTAZ611Se0KbPkcCX54BafhUlh1WvG
Login and  grant acces then press ENTER

"Decoder failed to handle oauth_token with data as returned by provider. A different decoder may be needed. Provider returned: b''"
ERROR LOGIN no GRANT ACCES

**Comment by rwelty1889** [comment]
behavior unchanged 10 days later.

**Comment by bogdans-telenav** [comment]
@rwelty1889 sorry for the late replay.
It looks like you are using a old version of the scrips.
I am figuring this out from the URL you posted in your previous message. 
The URL should be https.
This was fixed 2 months ago. [https://github.com/openstreetcam/upload-scripts/commit/4eb172a275726da1e3cb4621b53e19ce2db9ea0f](url)

**Comment by rwelty1889** [comment]
ok, but i'm using the url from the directions in the readme here on GitHub. maybe you should make sure those are up to date.

**Comment by rwelty1889** [comment]
ok, the only url in the process is the one that is spit out by docker for me to enter into my browser. i changed it to https and got no change in behavior.

**Comment by rwelty1889** [comment]
tried clearing my docker cache and images. no change in behavior.

**Comment by bogdans-telenav** [comment]
@rwelty1889 i will look into it more next week.

**Comment by rwelty1889** [comment]
any progress?

**Comment by bogdans-telenav** [comment]
Sorry not yet.

**Comment by alexandrui-telenav** [comment]
@rwelty1889 , unfortunately the original maintainer of the scripts is no longer involved in the project. Bogdan does some maintaining on the side but didn't look into this deep enough, it seems.

He's now in vacation for 2 weeks, if another user won't jump in to take a look it will take a while to see what's going on..

**Comment by rwelty1889** [comment]
i've refrained from making suggestions while you work through your process. but since the first reaction i got was that i was using outdated code, my first guess would be that the docker instance(s) didn't updated with the last round of bug fixes. but that's just a guess, i'm no docker expert, just a novice docker user.

**Comment by rwelty1889** [comment]
note that i am on vacation until sunday and wouldn't be able to try anything until i get home anyway.

**Comment by alexandrui-telenav** [comment]
good to hear @rwelty1889 , bogdan will come back soon and look into this

**Comment by bogdans-telenav** [comment]
@rwelty1889 started work on this. I will keep you posted.

**Comment by bogdans-telenav** [comment]
We made major changes to the upload scripts, unfortunately we temporary removed Docker support. Thanks for your patience! If you find any problem with the new version please create an issue and we will address it as soon as possible.
