### ISSUE TITLE
order of pictures is garbled

### ISSUE THREAD

**Issue by blaueente** [openstreetcam/upload-scripts#61]
I have processed my images according to:
1. make images with action cam + gpx logger
2. use josm to write gps data into exif
3. use mapillary_tools process to interpolate directions and prepare for mapillary upload
4. upload to mapillary
5. upload to osc using the upload script (multiple times resumed)

Problem: 
The order of the images is wrong, such that there are a lot of jumps, as you can see in
http://openstreetcam.org/details/1287365/1/track-info
results in a 390 km track instead of the actual 20 km, and the track presents as a large blob.

As the same image files seem to work with mapillary, there must be a problem with interpreting timestamps in osc.

**Comment by bogdans-telenav** [comment]
@blaueente sorry for the inconvenience. I am downloading your images to see if we can fix this issue server side with a post processing script.
Either way i am working on a new version of upload scripts that will tackle the issues of uploading and track discovery that we currently experience on the current upload scripts version.

**Comment by pkoby** [comment]
I'm having the same issue. For example: http://openstreetcam.org/details/1311657

I don't know if these sequences are somehow different than the ones from the month prior (the messed up ones are from Dec 2016, Nov 2016 was fine). The EXIF tags look the same as far as I can tell.

**Comment by bogdans-telenav** [comment]
Thanks for your patience we posted the new version of the upload scripts that should have addressed your issue. If you find any problem with the new version please create an issue and we will address it as soon as possible.
