### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by mds08011** [openstreetcam/upload-scripts#63]
Should `python upload_exif.py -p /Users/example/Desktop/Photos/AllPhotos/` instead be **python3** upload_exif.py -p /Users/example/Desktop/Photos/AllPhotos/?  I was getting errors related to the 'request' module when running the former.

**Comment by bogdans-telenav** [comment]
We massively changed the upload scripts. Now we support upload of exif data just by using the `python osc_tools.py upload -p PATH ` i think this should work without issues. If you find any please create an issue.
