### ISSUE TITLE
I was able to use upload photos by exif

### ISSUE THREAD

**Issue by kjartanbirgis** [openstreetcam/upload-scripts#64]
I was able to upload I can see the files on the server but  the console is just writting Retry attempt: increasing number, and on the server the photos didn't come at right order, is it possible to change it? How is it uploaded by filename or by date taken?

**Comment by mds08011** [comment]
A previous issue seems to indicate that `DateTimeOriginal` and `CreateDate` are used to dictate the order.

#61 

> I seem to have fixed it. If I remember correctly, around Dec 2016, I noticed that the timestamp on Mapillary wasn't accurate, so I started stripping DateTimeOriginal and CreateDate Exif tags so that Mapillary would read GPSDateTime as the correct one. Now I overwrite the former two tags with the GPSDateTime so that they all match, rather than having Mapillary read UTC time.
> 
> The upshot is that the sequences I was uploading to OSC were missing those tags, which I think is what the script reads to put them in order. What it was reading instead to put them into a pseudo-order I don't know. The command I used to write from the filename (which is the same as the correct timestamp) is:
> `exiftool "-createdate<filename" "-datetimeoriginal<filename" /DIRECTORY -overwrite_original `
> 
> If the tags exist, but are wrong, or your filename isn't the datetime, this should work:
> `exiftool "-AllDates<GPSDateTime" -overwrite_original /DIRECTORY`

**Comment by bogdans-telenav** [comment]
In the current version we are using the GPSDateTime. @mds08011 was correct.
