### ISSUE TITLE
Python 3.6 is Not Widely Available

### ISSUE THREAD

**Issue by alrs** [openstreetcam/upload-scripts#67]
This software does not run on Debian (or Raspbian) out-of-the-box, as it uses the PEP 526 variable annotations that only exist in Python 3.6.

Are you amenable to fixing this? I've submitted a [PR](https://github.com/openstreetcam/upload-scripts/pull/66) to aid in getting Python 3 with `virtualenv` as described in the README.

**Comment by bogdans-telenav** [comment]
@alrs as you saw I used type suggestions quite a lot, and it would be 2-3 days of work to remove it. is there any way that you could use Python 3.6 or is there any reason not to use it?

**Comment by ToeBee** [comment]
Is this what is causing a syntax error  at `parser: ArgumentParser = ArgumentParser(prog='python osc_tools.py',`? 

I'm running Linux Mint 18.3 which is an LTS supported until 2021. It is based on Ubuntu 16.04 and does not seem to have python 3.6 available in normal package repos. It looks like I might be able to add a PPA to get it installed though.

**Comment by alrs** [comment]
I went through the code and saw how hard it would be to back out all the 3.6 stuff.

@bogdans-telenav it's not particularly clean to install random versions of Python on a system like Linux where most things are package managed, so it's not a simple thing like using `brew install` or whatever it is people do on Windows. Unlike Windows and MacOS, parts of the Linux operating system use Python, so it's dangerous to mess with your Python version without potentially breaking your system.

Type safety is great, so I can see why you wouldn't want to lose annotations.

I have a [PR](https://github.com/openstreetcam/upload-scripts/pull/71)  in to add Docker support, so that Linux people can use this in a Docker container that has Python 3.7.2.

**Comment by bogdans-telenav** [comment]
@ToeBee yes
