### ISSUE TITLE
how to upload a folder with images? (not a sequence)

### ISSUE THREAD

**Issue by mfa** [openstreetcam/upload-scripts#72]
I record images using a gopro and uploaded them with ``upload_exif.py``.
How to upload a folder with images now?

**Comment by bogdans-telenav** [comment]
python osc_tools.py upload -p folder_with_images

**Comment by mfa** [comment]
response:
```
Searching for sequences...
Search completed.
    No sequence found.
```

In the folder are 1500 files, i.e. G0016767.JPG

**Comment by bogdans-telenav** [comment]
Interesting, can you send me a sample of let's say the first 2 images? and/ or the OSC_log.log file found where you have the scripts.

**Comment by mfa** [comment]
https://paste.madflex.de/PQPF6Hmf#debug_image_upload.zip

**Comment by bogdans-telenav** [comment]
@mfa i started investigating.

**Comment by bogdans-telenav** [comment]
@mfa fixed your issue with [commit](https://github.com/openstreetcam/upload-scripts/commit/16e9d3e3729a024cdfea7a183ece762952d5eab3). Thanks for reporting. Please close this after you confirm that all works as expected.

**Comment by mfa** [comment]
thx. upload works now.
