### ISSUE TITLE
No sequence found

### ISSUE THREAD

**Issue by mishari** [openstreetcam/upload-scripts#74]
Hi

I have a directory containing almost 30k files of captures made over a month.
```
$ ls|head
0000001.jpg
0000002.jpg
0000003.jpg
0000004.jpg
0000005.jpg
0000006.jpg
0000007.jpg
0000008.jpg
0000009.jpg
0000010.jpg
```

I ran the osc_tool script as follows

```
python ~/upload-scripts/osc_tools.py upload -p .
```

The output I get is

```
Searching for sequences...
Search completed.
    No sequence found.
```

I'm not sure what I'm missing?

**Comment by bogdans-telenav** [comment]
@mishari can you post the OSC_

**Comment by bogdans-telenav** [comment]
@mishari your images missed GPS timestamp and we ignored exif timestamp. Fixed this issue by falling back on exif timestamp if GPS timestamp was not found.
