### ISSUE TITLE
Re-upload after deleting

### ISSUE THREAD

**Issue by mds08011** [openstreetcam/upload-scripts#78]
I recently uploaded photos and then deleted them from openstreetcam.org because were not appearing in the correct location (the issue has now been fixed: #76).  However, now that I am trying to re-upload them, I am being told that my images are already uploaded.

`Found sequence at path _____ that is already uploaded at https://api.openstreetcam.org/details/1342267`

Is there anything I should do to get around this?  Should I just wait longer?

**Comment by bogdans-telenav** [comment]
In the folder at path "_____" you will find 2 files "osc_sequence_id.txt" and "osc_sequence_upload_progress.txt" you need to remove both files in order to be able to upload your images again.

**Comment by mds08011** [comment]
That worked!  Thank you!
