### ISSUE TITLE
Requires Python 3.6

### ISSUE THREAD

**Issue by bikeoid** [openstreetcam/upload-scripts#81]
I followed the instructions to install into Windows Bash shell, where my default Python Version was 3.5.  It took a bit of searching to discover that the resulting "syntax error" really meant that at minimum 3.6 is required.    Once I knew that, I could track down a newer version.

  The Readme.MD only mentions Python 3, but should read that it requires Python 3.6.

**Comment by amilopowers** [comment]
Thanks for you help @bikeoid 

I stumble over this problem over and over again.
