### ISSUE TITLE
Uploading Video From Tesla Dashcams

### ISSUE THREAD

**Issue by brandongalbraith** [openstreetcam/upload-scripts#93]
I am exploring capturing video from Tesla dashcams as well as GPX data using https://github.com/marcone/teslausb. My understanding is that the Tesla vehicle cameras capture at 720p resolution (4Mb bit rate). Does this meet the requirements for uploading for openstreetcam processing?

**Comment by alexandrui-telenav** [comment]
This sounds very very cool @brandongalbraith. Resolution and bitrate do sound a bit low but would definitely give it a try to see the detection results. 
Let us know if there's something we can help with.

**Comment by brandongalbraith** [comment]
Did some tests on the resulting video output, and wasn't terribly excited with the results (versus what's possible with cheap action cams). Closing this for now until there's a bump in specs on Tesla cam hardware.

**Comment by Alevale** [comment]
@brandongalbraith Even though the quality might not exceed expectations it might be better than nothing and more up to date than what google might offer, so would you mind sharing the script you used?

Or you didn't even spend time into scripting after realising the video output quality wasn't great.
